// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Default [FirebaseOptions] for use with your Firebase apps.
//
// Example:
// ```dart
// import 'firebase_options.dart';
// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABmGEfavx3KdIkuIWwWqUwnt8sp38CzWg',
    appId: '1:873594167994:web:a004d8fd0d1877106d5883',
    messagingSenderId: '873594167994',
    projectId: 'homemate-13d3d',
    authDomain: 'homemate-13d3d.firebaseapp.com',
    storageBucket: 'homemate-13d3d.firebasestorage.app',
    measurementId: 'G-03P5Z4MDJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSHLwU7fSNKRoNjbFWDcCQb2v9TfO5lIc',
    appId: '1:873594167994:android:ba078e60ab52d2276d5883',
    messagingSenderId: '873594167994',
    projectId: 'homemate-13d3d',
    storageBucket: 'homemate-13d3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzXMuyqqk6bVSW7AHxm8ZjE8T8-8n8UKw',
    appId: '1:873594167994:ios:1f04adb2315a823a6d5883',
    messagingSenderId: '873594167994',
    projectId: 'homemate-13d3d',
    storageBucket: 'homemate-13d3d.firebasestorage.app',
    iosBundleId: 'com.example.homemate2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzXMuyqqk6bVSW7AHxm8ZjE8T8-8n8UKw',
    appId: '1:873594167994:ios:1f04adb2315a823a6d5883',
    messagingSenderId: '873594167994',
    projectId: 'homemate-13d3d',
    storageBucket: 'homemate-13d3d.firebasestorage.app',
    iosBundleId: 'com.example.homemate2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABmGEfavx3KdIkuIWwWqUwnt8sp38CzWg',
    appId: '1:873594167994:web:da553158f686057e6d5883',
    messagingSenderId: '873594167994',
    projectId: 'homemate-13d3d',
    authDomain: 'homemate-13d3d.firebaseapp.com',
    storageBucket: 'homemate-13d3d.firebasestorage.app',
    measurementId: 'G-2SPHG6SYT4',
  );
}
